PREDEFINED_FIELDS = {
    'SC0011': {
        'fields': {
            'ID_DOC': 'VARCHAR(255)',
            'NUM_DOC': 'VARCHAR(255)',
            'FEC_DOC': 'DATE',
            'COD_PAC': 'VARCHAR(255)',
            'NOM_PAC': 'VARCHAR(255)',
            'COD_EMP': 'VARCHAR(255)',
            'NUM_CIA': 'VARCHAR(255)',
            'DOCATE': 'VARCHAR(255)',
            'HI_DOC': 'VARCHAR(255)',
            'COD_SER': 'VARCHAR(255)',
            'MI_DOC': 'VARCHAR(255)',
            'COD_DX': 'VARCHAR(255)',
            'TA_DOC': 'VARCHAR(255)',
            'TOT_DOC': 'DECIMAL(10,2)',
            'CLOS_DOC': 'BOOLEAN',
        },
        'primary_key': 'NUM_DOC'
    },
    'SC0006': {
        'fields': {
            'COD_SER': 'VARCHAR(255)',
            'NOM_SER': 'VARCHAR(255)',
            'TPROF_SER': 'VARCHAR(255)',
            'CMP_SER': 'VARCHAR(255)',
            'TIP_SER': 'VARCHAR(255)',
            'DIR_SER': 'VARCHAR(255)',
            'TEL_SER': 'VARCHAR(255)',
            'ESP_SER': 'VARCHAR(255)',
            'FNAC_SER': 'DATE',
            'PAG_SER': 'BOOLEAN',
            'COS_SER': 'DECIMAL(10,2)',
            'PRC_SER': 'DECIMAL(10,2)',
            'CC_SER': 'DECIMAL(10,2)',
            'CM_SER': 'DECIMAL(10,2)',
            'CE_SER': 'DECIMAL(10,2)',
            'PTS_SER': 'BOOLEAN',
            'DES_SER': 'BOOLEAN',
            'PSS_SER': 'BOOLEAN',
            'IND_SER': 'BOOLEAN',
            'TD_SER': 'VARCHAR(255)',
            'DNI_SER': 'VARCHAR(255)',
            'USUM_SIS': 'VARCHAR(255)',
            'TPROF1_SER': 'VARCHAR(255)',
            'ESPA_SER': 'VARCHAR(255)',
            'ESPH_SER': 'VARCHAR(255)',
            'ESPE_SER': 'VARCHAR(255)',
            'NCO_SER': 'VARCHAR(255)',
            'NOM_MED': 'VARCHAR(255)',
            'SAL_SER': 'INT'
        },
        'primary_key': 'COD_SER'
    },
    'SC0003': {
        'fields': {
            'COD_EMP': 'VARCHAR(255)',
            'ID_CIA': 'VARCHAR(255)',
            'ID_EMP': 'VARCHAR(255)',
            'NOM_EMP': 'VARCHAR(255)',
            'TEL_EMP': 'VARCHAR(255)',
            'DIR_EMP': 'VARCHAR(255)',
            'MONEDA_EMP': 'VARCHAR(255)',
            'FAC_EMP': 'DECIMAL(10,2)',
            'ACOA_EMP': 'DECIMAL(10,2)',
            'ACFA_EMP': 'DECIMAL(10,2)',
            'ADED_EMP': 'DECIMAL(10,2)',
            'HCOA_EMP': 'DECIMAL(10,2)',
            'HDED_EMP': 'DECIMAL(10,2)',
            'RUC_EMP': 'VARCHAR(255)',
            'FCIA_EMP': 'BOOLEAN',
            'OBS_EMP': 'VARCHAR(255)',
            'USU_SIS': 'VARCHAR(255)',
            'FHC_SIS': 'VARCHAR(255)',
            'EST_EMP': 'DECIMAL(10,2)'
        },
        'primary_key': 'COD_EMP'
    },
    'SC0004': {
        'fields': {
            'ID_PAC': 'VARCHAR(255)',
            'ID_CIA': 'VARCHAR(255)',
            'ID_EMP': 'VARCHAR(255)',
            'COD_PAC': 'VARCHAR(255)',
            'COD_TIT': 'VARCHAR(255)',
            'COD_EMP': 'VARCHAR(255)',
            'CAT_PAC': 'VARCHAR(255)',
            'NOM_PAC': 'VARCHAR(255)',
            'DIR_PAC': 'VARCHAR(255)',
            'TEL_PAC': 'VARCHAR(255)',
            'FNAC_PAC': 'DATE',
            'CARNET_PAC': 'VARCHAR(255)',
            'DNI_PAC': 'VARCHAR(255)',
            'EC_PAC': 'VARCHAR(255)',
            'SEX_PAC': 'VARCHAR(255)',
            'NH_PAC': 'VARCHAR(255)',
            'RUC_PAC': 'VARCHAR(255)',
            'USU_SIS': 'VARCHAR(255)',
            'CUP_PAC': 'VARCHAR(255)',
            'TDI_PAC': 'VARCHAR(255)',
            'UC_SIS': 'VARCHAR(255)',
            'EST_PAC': 'DECIMAL(10,2)',
            'NUM_DOC': 'VARCHAR(255)'  # Llave foránea
        },
        'primary_key': 'ID_PAC'
    },
    'SC0033': {
        'fields': {
            'ID_DEV': 'VARCHAR(255)',
            'FH_DEV': 'VARCHAR(255)',
            'PER_DEV': 'VARCHAR(255)',
            'NUM_FAC': 'VARCHAR(255)',
            'FEC_FAC': 'DATE',
            'TOT_FAC': 'DECIMAL(10,2)',
            'COD_CIA': 'VARCHAR(255)',
            'NOM_CIA': 'VARCHAR(255)',
            'NUM_DOC': 'VARCHAR(255)',  # Llave foránea
            'FEC_DOC': 'DATE',
            'TA_DOC': 'VARCHAR(255)',
            'COD_PAC': 'VARCHAR(255)',
            'NOM_PAC': 'VARCHAR(255)',
            'COD_SER': 'VARCHAR(255)',
            'NOM_SER': 'VARCHAR(255)',
            'TIP_DEV': 'VARCHAR(255)',
            'MOT_DEV': 'TEXT',
            'USU_DEV': 'VARCHAR(255)',
            'FAC_DEV': 'BOOLEAN',
            'SOL_DEV': 'VARCHAR(255)',
            'OBS_DEV': 'TEXT',
            'UC_SIS': 'VARCHAR(255)',
            'UM_SIS': 'VARCHAR(255)',
            'FC_SIS': 'VARCHAR(255)',
        },
        'primary_key': 'ID_DEV'
    },
    'SC0017': {
        'fields': {
            'NUM_FAC': 'VARCHAR(255)',
            'NUM_DOC': 'VARCHAR(255)',  # Llave foránea
            'COD_PAC': 'VARCHAR(255)',
            'NOM_PAC': 'VARCHAR(255)',
            'COD_TIT': 'VARCHAR(255)',
            'COD_EMP': 'VARCHAR(255)',
            'CIA_FAC': 'VARCHAR(255)',
            'RUC_FAC': 'VARCHAR(255)',
            'FEC_FAC': 'DATE',
            'HOR_FAC': 'VARCHAR(255)',
            'DIR_FAC': 'VARCHAR(255)',
            'ST_FAC': 'DECIMAL(10,2)',
            'DED_FAC': 'DECIMAL(10,2)',
            'COA_FAC': 'DECIMAL(10,2)',
            'VV_FAC': 'DECIMAL(10,2)',
            'IGV_FAC': 'DECIMAL(10,2)',
            'EXO_FAC': 'DECIMAL(10,2)',
            'TOT_FAC': 'DECIMAL(10,2)',
            'PCF_FAC': 'DECIMAL(10,2)',
            'PC_FAC': 'DECIMAL(10,2)',
            'TIP_FAC': 'VARCHAR(255)',
            'ANU_FAC': 'BOOLEAN',
            'PAG_FAC': 'BOOLEAN',
            'NC_FAC': 'BOOLEAN',
            'NUM_NC': 'VARCHAR(255)',
            'GNC': 'BOOLEAN',
            'AGRUPA': 'BOOLEAN',
            'CDO_FAC': 'BOOLEAN',
            'USU_SIS': 'VARCHAR(255)',
            'ARE_FAC': 'VARCHAR(255)',
            'ENV_FAC': 'BOOLEAN',
            'EE_FAC': 'VARCHAR(255)',
            'DEDE_FAC': 'DECIMAL(10,2)',
            'COAE_FAC': 'VARCHAR(255)',
            'HAS_FAC': 'VARCHAR(255)',
            'TP_CP': 'VARCHAR(255)',
            'PE_CP': 'DECIMAL(10,2)',
            'PT_CP': 'DECIMAL(10,2)',
            'MDIG_CP': 'VARCHAR(255)',
            'TDIG_CP': 'VARCHAR(255)',
            'ID_PAR': 'VARCHAR(255)',
            'ID_CJ': 'VARCHAR(255)',
            'UC_SIS': 'VARCHAR(255)',
            'FC_SIS': 'VARCHAR(255)',
            'UM_SIS': 'VARCHAR(255)',
        },
        'primary_key': 'NUM_FAC'
    },
    'SC0002': {
        'fields': {
            'ID_CIA': 'VARCHAR(255)',
            'COD_CIA': 'VARCHAR(255)',
            'NOM_CIA': 'VARCHAR(255)',
            'TEL_CIA': 'VARCHAR(255)',
            'DIR_CIA': 'VARCHAR(255)',
            'RUC_CIA': 'VARCHAR(255)',
            'CONS_CIA': 'DECIMAL(10,2)',
            'NUM_CIA': 'DECIMAL(10,2)',
            'DF_CIA': 'DECIMAL(10,2)',
            'CONV_CIA': 'DECIMAL(10,2)',
            'TF_CIA': 'VARCHAR(255)',
            'CON_CIA': 'BOOLEAN',
        },
        'primary_key': 'ID_CIA'
    },
    'SC0012': {
        'fields': {
            'NUM_DOC': 'VARCHAR(255)',  # Llave foránea
            'POS_SER': 'INT',
            'FEC_SER': 'DATE',
            'COD_SEG': 'VARCHAR(255)',
            'COD_SER': 'VARCHAR(255)',
            'FUN_SER': 'VARCHAR(255)',
            'CAN_SER': 'DECIMAL(10,2)',
            'IMP_SER': 'DECIMAL(10,2)',
            'HM_SER': 'DECIMAL(10,2)',
            'GNC_SER': 'BOOLEAN',
            'REC_SER': 'BOOLEAN',
            'TOT_SER': 'DECIMAL(10,2)',
            'TIGV_SER': 'DECIMAL(10,2)',
            'COP_SER': 'DECIMAL(10,2)',
            'EXO_SER': 'BOOLEAN',
            'CODRUB': 'VARCHAR(255)',
            'ICOD_SER': 'VARCHAR(255)',
            'ARE_SER': 'VARCHAR(255)',
            'TS_SER': 'DECIMAL(10,2)',
            'PCOA_SER': 'DECIMAL(10,2)',
            'PAG_SER': 'BOOLEAN',
            'NUM_CP': 'VARCHAR(255)',
            'REF_SER': 'VARCHAR(255)',
            'UC_SIS': 'VARCHAR(255)',
            'FHC_SIS': 'VARCHAR(255)',
            'UM_SIS': 'VARCHAR(255)',
            'DTO_SER': 'DECIMAL(10,2)',
            'ISDTO_SER': 'DECIMAL(10,2)',
        }
    },
    'SC0022': {
        'fields': {
            'NUM_PAG': 'VARCHAR(255)',
            'NUM_FAC': 'VARCHAR(255)',
            'FEC_FAC': 'DATE',
            'NUM_DOC': 'VARCHAR(255)',  # Llave foránea
            'TOT_FAC': 'DECIMAL(10,2)',
            'ORI_PAG': 'VARCHAR(255)',
            'NUM_NC': 'VARCHAR(255)'
        },
    }
}
